# Generated by Django 5.2.10 on 2026-01-24 22:01

import airport_service.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport_service", "0002_airplanetype_crew_alter_country_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name_plural": "Cities"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"], "verbose_name_plural": "Countries"},
        ),
        migrations.AlterField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=airport_service.models.airplane_image_file_path,
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="airplane",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flights",
                to="airport_service.airplane",
            ),
        ),
    ]
